baseURL = "https://kifish.github.io/"
languageCode = "en-us"
title = "kifish's blog"
theme = "github.com/adityatelange/hugo-PaperMod"

[params]
  mainSections = [""]
  disableKinds = ["taxonomy", "term"]
